Update setup-debian-xfce

diff --git a/Distribution/Debian/Scripts/DesktopEnv/XFCE/setup-debian-xfce b/Distribution/Debian/Scripts/DesktopEnv/XFCE/setup-debian-xfce
--- a/Distribution/Debian/Scripts/DesktopEnv/XFCE/setup-debian-xfce
+++ b/Distribution/Debian/Scripts/DesktopEnv/XFCE/setup-debian-xfce
@@ -3,13 +3,21 @@
 ### A Mobilinux Component.
 ### This will prepend all the functions needed for installation
 
+### Color Input Environment Variables
+RED="$(tput setaf 1)"
+GREEN="$(tput setaf 2)"
+YELLOW="$(tput setaf 3)"
+BLUE="$(tput setaf 4)"
+BOLD="$(tput bold)"
+NOATTR="$(tput sgr0)"
+
 set -e -u
 
 ### Check if Network Connection is present
 if ping -c 1 8.8.8.8 >/dev/null 2>&1; then
     true
 else
-    echo "Cannot continue the installation. Please Check your network connection"
+    echo "${RED}${BOLD}Cannot continue the installation. Please Check your network connection${NOATTR}"
     exit 2
 fi
 
@@ -17,30 +25,30 @@ fi
 if [ ! -e /usr/lib/.libdone.so.9 ]; then
     true
 else
-    echo "We detected that you are running it inside the distro: incorrect syntax"
+    echo "${RED}${BOLD}We detected that you are running it inside the distro: incorrect syntax${NOATTR}"
     exit 2
 fi
 
 if [ ! -e /usr/ ]; then
     true
 else
-    echo "We detected that you are running it inside the distro: incorrect syntax"
-    exit 2
+     echo "${RED}${BOLD}We detected that you are running it inside the distro: incorrect syntax${NOATTR}"
+     exit 2
 fi
 
 ### At this point check for curl command. if not installed. ask a user to install it then abort
 if which curl >/dev/null 2>&1; then
     true
 else
-    echo "Cannot find command 'curl'. Please install it by typing 'pkg in curl'"
-    exit 2
+    echo "${RED}${BOLD}Cannot find command 'curl'. Please install it by typing 'pkg in curl'${NOATTR}"
+   exit 2
 fi
 
 ### Next is to check if debian.deb is installed
 if which debian >/dev/null 2>&1; then
     true
 else
-    echo "Cannot install debian.deb. Please Install it"
+    echo "${RED}${BOLD}Cannot find configuration files. Please uninstall and install again.${NOATTR}"
     exit 2
 fi
 
@@ -48,7 +56,7 @@ fi
 if debian -- true >/dev/null 2>&1; then
     true
 else
-    echo "It seems Debian isn't installed. Please Install it"
+    echo "${RED}${BOLD}It seems Debian isn't installed. Please Install it first.${NOATTR}"
     exit 2
 fi
 
@@ -56,16 +64,45 @@ fi
 if debian -- which apt >/dev/null 2>&1; then
     true
 else
-    echo "It seems you're using a custom distributions which is not supported yet. please use Debian Instead"
-    exit 2
+     echo "${RED}${BOLD}It seems you're using a custom distributions which is not supported yet. please use Debian Instead.${NOATTR}"
+     exit 2
 fi
 
-### Function Time
+### Install XFCE 
 install_xfce() {
     if ! debian -- which startxfce4 >/dev/null 2>&1; then
-        echo "Installing Xfce4 base package... "
-        debian -- sudo apt install xfce4 -yy
-        dpkg --configure -a
+    dialog --clear --backtitle "System Installation Type" --title "Choose Installation type:" --menu "Please select:" 10 45 3 1 "Minimal Installation 1.5GB" 2 "Full Installation 4GB" 2>temp
+# OK is pressed
+        if [ "$?" = "0" ]
+                then
+                    _return=$(cat temp)
+ 
+                                # Minimal is selected
+                                if [ "$_return" = "1" ]
+                                then
+                                      echo "${GREEN}${BOLD}Installing Minimal Desktop Environment...${NOATTR}"
+                                      sleep 4
+                                      debian -- sudo apt-get install xfce4 xfce4-terminal -yy
+                                      dpkg --configure -a
+                                fi
+ 
+                                         # Full is selected
+                                        if [ "$_return" = "2" ]
+                                        then
+                                            echo "${GREEN}${BOLD}Installing Full Desktop Environment...${NOATTR}"
+                                            sleep 4
+                                            debian -- sudo apt-get install xfe xfce4 xfce4-terminal xfce4-goodies gimp neofetch libreoffice task-xfce-desktop -yy
+                                            dpkg --configure -a
+                                       fi
+ # Cancel is pressed
+else
+    echo "${GREEN}${BOLD}Cancel is pressed, Restarting The Menu.....${NOATTR}"
+	sleep 3
+	dialog --menu "Choose Installation type:" 10 40 3 1 "Minimal Installation 1.5GB" 2 "Full Installation 4GB" 2>temp
+fi
+# remove the temp file
+rm -f temp
+   
         setup_tigervnc
     else
         echo "Found xfce package. Skipping Install and Performing an autoconfiguration to tigervnc"
@@ -90,7 +127,7 @@ perform_config()
     echo "Downloading the wrapper script..."
     echo ""
     rm -rf $PREFIX/bin/startxfce-debian
-    curl -O --retry 5 --output-dir $PREFIX/bin/ https://raw.githubusercontent.com/MobilinuxApp/Mobilinux-CLI/master/Distribution/Debian/Scripts/DesktopEnv/XFCE/bin/startxfce-debian
+    wget --tries=20 https://raw.githubusercontent.com/MobilinuxApp/Mobilinux-CLI/master/Distribution/Debian/Scripts/DesktopEnv/XFCE/bin/startxfce-debian -O $PREFIX/bin/startxfce-debian
     chmod 777 $PREFIX/bin/startxfce-debian
     echo ""
     echo "Finalizing..."
